name: kidney
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - pytorch-cuda=12.1
  - numpy
  - pandas
  - scikit-learn
  - scikit-image
  - matplotlib
  - seaborn
  - jupyter
  - ipykernel
  - tqdm
  - pyyaml
  - pip
  - pip:
      - monai
      - nibabel
      - pydicom
      - SimpleITK
      - opencv-python
      - albumentations
      - tensorboard
      - kaggle